version: "3"
services:
  backend:
    image: ghcr.io/integrated-project-int221/backend:master
    ports:
       - "3000:8080"
networks:
  default:
    external:
      name: database_myproduct-network
